# Codecov configuration file
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "examples/*"
  - "tests/*"
  - "benches/*"
  - "fuzz/*"
  - "fuzz_targets/*"
  - "target/*"
