# Cargo-deny configuration for rskv project

[advisories]
# 安全公告数据库
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = []

[licenses]
# 许可证检查
# 允许的许可证
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "Unicode-3.0",
]

# 许可证例外
exceptions = [
    # 允许一些工具使用 GPL 许可证
    { name = "criterion", allow = ["MIT", "Apache-2.0"] },
]

[bans]
# 禁止的依赖
multiple-versions = "warn"
# 禁止使用特定版本的依赖
deny = [
    # 禁止使用不安全的依赖
    { name = "memmap", version = "=0.7.0", reason = "Use memmap2 instead" },
]

# 允许的依赖
allow = [
    # 核心依赖
    { name = "tokio", version = "1.0" },
    { name = "crossbeam-epoch", version = "0.9" },
    { name = "dashmap", version = "5.0" },
    { name = "rayon", version = "1.0" },
    { name = "serde", version = "1.0" },
    { name = "bincode", version = "1.0" },
    { name = "thiserror", version = "1.0" },
    { name = "parking_lot", version = "0.12" },
    { name = "ahash", version = "0.8" },
    { name = "memmap2", version = "0.9" },
    { name = "log", version = "0.4" },
    { name = "env_logger", version = "0.10" },
    # 开发依赖
    { name = "criterion", version = "0.5" },
    { name = "tempfile", version = "3.0" },
    # 系统相关依赖
    { name = "windows-sys", version = "*" },
    { name = "windows-targets", version = "*" },
    { name = "windows_aarch64_gnullvm", version = "*" },
    { name = "windows_aarch64_msvc", version = "*" },
    { name = "windows_i686_gnu", version = "*" },
    { name = "windows_i686_gnullvm", version = "*" },
    { name = "windows_i686_msvc", version = "*" },
    { name = "windows_x86_64_gnu", version = "*" },
    { name = "windows_x86_64_gnullvm", version = "*" },
    { name = "windows_x86_64_msvc", version = "*" },
    { name = "wasi", version = "*" },
    { name = "wit-bindgen-rt", version = "*" },
    { name = "zerocopy", version = "*" },
    { name = "wasm-bindgen", version = "*" },
    { name = "wasm-bindgen-backend", version = "*" },
    { name = "wasm-bindgen-macro", version = "*" },
    { name = "wasm-bindgen-macro-support", version = "*" },
    { name = "wasm-bindgen-shared", version = "*" },
    { name = "web-sys", version = "*" },
    { name = "js-sys", version = "*" },
    { name = "winapi-util", version = "*" },
    { name = "windows-link", version = "*" },
    { name = "plotters", version = "*" },
    { name = "getrandom", version = "*" },
    { name = "rustix", version = "*" },
    { name = "errno", version = "*" },
    { name = "libc", version = "*" },
    { name = "mio", version = "*" },
    { name = "socket2", version = "*" },
    { name = "backtrace", version = "*" },
    { name = "parking_lot_core", version = "*" },
    { name = "is-terminal", version = "*" },
    { name = "termcolor", version = "*" },
    { name = "same-file", version = "*" },
    { name = "walkdir", version = "*" },
    { name = "proc-macro2", version = "*" },
    { name = "quote", version = "*" },
    { name = "syn", version = "*" },
    { name = "serde_derive", version = "*" },
    { name = "serde_json", version = "*" },
    { name = "num-traits", version = "*" },
    { name = "thiserror-impl", version = "*" },
    { name = "lock_api", version = "*" },
    { name = "scopeguard", version = "*" },
    { name = "smallvec", version = "*" },
    { name = "rayon-core", version = "*" },
    { name = "crossbeam-utils", version = "*" },
    { name = "crossbeam-channel", version = "*" },
    { name = "crossbeam-deque", version = "*" },
    { name = "num_cpus", version = "*" },
    { name = "cfg-if", version = "*" },
    { name = "once_cell", version = "*" },
    { name = "regex", version = "*" },
    { name = "regex-syntax", version = "*" },
    { name = "aho-corasick", version = "*" },
    { name = "memchr", version = "*" },
    { name = "thread_local", version = "*" },
    { name = "version_check", version = "*" },
    { name = "autocfg", version = "*" },
    { name = "cc", version = "*" },
    { name = "pkg-config", version = "*" },
    { name = "vcpkg", version = "*" },
    # 更多间接依赖
    { name = "addr2line", version = "*" },
    { name = "adler2", version = "*" },
    { name = "anes", version = "*" },
    { name = "anstyle", version = "*" },
    { name = "bitflags", version = "*" },
    { name = "bumpalo", version = "*" },
    { name = "bytes", version = "*" },
    { name = "cast", version = "*" },
    { name = "ciborium", version = "*" },
    { name = "ciborium-io", version = "*" },
    { name = "ciborium-ll", version = "*" },
    { name = "clap", version = "*" },
    { name = "clap_builder", version = "*" },
    { name = "clap_lex", version = "*" },
    { name = "criterion-plot", version = "*" },
    { name = "crunchy", version = "*" },
    { name = "either", version = "*" },
    { name = "fastrand", version = "*" },
    { name = "gimli", version = "*" },
    { name = "half", version = "*" },
    { name = "hashbrown", version = "*" },
    { name = "hermit-abi", version = "*" },
    { name = "humantime", version = "*" },
    { name = "io-uring", version = "*" },
    { name = "itertools", version = "*" },
    { name = "itoa", version = "*" },
    { name = "linux-raw-sys", version = "*" },
    { name = "miniz_oxide", version = "*" },
    { name = "object", version = "*" },
    { name = "oorandom", version = "*" },
    { name = "pin-project-lite", version = "*" },
    { name = "plotters-backend", version = "*" },
    { name = "plotters-svg", version = "*" },
    { name = "r-efi", version = "*" },
    { name = "redox_syscall", version = "*" },
    { name = "regex-automata", version = "*" },
    { name = "rustc-demangle", version = "*" },
    { name = "rustversion", version = "*" },
    { name = "ryu", version = "*" },
    { name = "signal-hook-registry", version = "*" },
    { name = "slab", version = "*" },
    { name = "tinytemplate", version = "*" },
    { name = "tokio-macros", version = "*" },
    { name = "unicode-ident", version = "*" },
    { name = "rskv", version = "*" },
]

[sources]
# 源配置
unknown-registry = "deny"
unknown-git = "deny"
