# Rustfmt configuration for rskv project

max_width = 100
tab_spaces = 4
edition = "2021"
newline_style = "Unix"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Formatting
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true

# Code style
use_small_heuristics = "Default"
fn_single_line = false
where_single_line = false
empty_item_single_line = true
struct_lit_single_line = true
trailing_semicolon = true
trailing_comma = "Vertical"