name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # 每周一凌晨2点运行
    - cron: '0 2 * * 1'

env:
  CARGO_TERM_COLOR: always

jobs:
  # 代码质量检查
  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-quality-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-quality-cargo-

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Install cargo-geiger
        run: cargo install cargo-geiger

      - name: Install cargo-deadlinks
        run: cargo install cargo-deadlinks

      - name: Run cargo-audit
        run: cargo audit

      - name: Run cargo-deny
        run: cargo deny check

      - name: Run cargo-geiger
        run: cargo geiger --all-features --workspace

      - name: Run cargo-deadlinks
        run: |
          cargo doc --all-features --no-deps --document-private-items
          cargo deadlinks --dir target/doc